# Generated by Django 6.0.1 on 2026-03-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], default='READY', max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_time_ms', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('IT', 'IT Manager'), ('LEGAL', 'Legal Counsel'), ('CEO', 'CEO')], max_length=10)),
                ('trigger_time_ms', models.BigIntegerField()),
                ('message', models.TextField()),
                ('decision_prompt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(blank=True, null=True)),
                ('responded_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('is_missed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simulationevent')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simulation')),
            ],
        ),
    ]
